packages:
 - 'packages/backend'
 - 'packages/frontend'
 - 'packages/sw'
 - 'packages/misskey-js'
 - 'packages/misskey-js/generator'
 - 'packages/misskey-reversi'
 - 'packages/misskey-bubble-game'
 - 'packages/megalodon'
